---
- hosts: dot3
  connection: local
  gather_facts: no

  vars:
    template_file: './bulkAaepBindingsTemplate.j2'
    output_file: './bulkAaepBindingsRendered.json'
    aaep_dn: "uni/infra/attentp-A"  
    aaep_name: "A"
    url: "/api/node/mo/uni/infra/attentp-A.json"
  tasks:
    - name: Import EPG definitions
      include_vars:
        file: './bulkAaepBindingsDefinitions.vars'
    - name: Render bulk ACI configuration
      template:
        src: "{{ template_file }}" 
        dest: "{{ output_file }}"
    - name: Log into APIC 
      ansible.builtin.uri:
        url: 'https://{{inventory_hostname}}/api/aaaLogin.json'
        return_content: true
        validate_certs: false
        body_format: json
        # aci_username and aci_password come from inventory file
        body: '{"aaaUser":{"attributes":{"name":"{{aci_username }}","pwd":"{{aci_password}}"}}}'
        method: POST
      register: this
      delegate_to: localhost
    - name: Display auth cookie
      debug:
        var: this.cookies_string
    - name: Store auth cookie
      ansible.builtin.set_fact:
        aciCookie: '{{ this.set_cookie }}'
    - name: Load and parse POST content
      vars:
        parsed_file: "{{ lookup('file', output_file) | from_json }}"
      set_fact:
        url: "{{ parsed_file | json_query('url') }}"
        payload: "{{ parsed_file | json_query('payload') }}"
    - name: POST raw content to APIC in one shot
      ansible.builtin.uri:
        url: 'https://{{ inventory_hostname }}{{ url }}'
        return_content: true
        validate_certs: false
        body_format: json
        method: POST
        headers:
          Cookie: "{{ aciCookie }}"
        body: "{{ payload }}"
      register: that
      delegate_to: localhost
      when: aciCookie is defined 
